#ifndef __IMFDEFINITIONS_H__
#define __IMFDEFINITIONS_H__

#define IMF_TYPE_EOF 0
#define IMF_TYPE_MODEL 1
#define IMF_TYPE_TEXTURE 2
#define IMF_TYPE_FONT 3
#define IMF_TYPE_TREE 4
#define IMF_TYPE_MATRIX_LANDSCAPE 5
#define IMF_TYPE_SHADER 6
#define IMF_TYPE_SHADER_PROGRAM 7
#define IMF_TYPE_COLLISION_OBJECT 8
#define IMF_TYPE_SOUND_OBJECT 9


#define IMF_SHADER_TYPE_NULL 0
#define IMF_SHADER_TYPE_VERTEX 1
#define IMF_SHADER_TYPE_FRAGMENT 2
#define IMF_SHADER_TYPE_GEOMETRY 3

#define IMF_MODEL_VERTEX 1
#define IMF_MODEL_NORMALS 2
#define IMF_MODEL_UVS 4
#define IMF_MODEL_FACES 8

#endif
