#ifndef __IMFDEFINITIONS_H__
#define __IMFDEFINITIONS_H__

#define IMF_TYPE_EOF 0
#define IMF_TYPE_MODEL 1
#define IMF_TYPE_TEXTURE 2
#define IMF_TYPE_FONT 3
#define IMF_TYPE_TREE 4
#define IMF_TYPE_MATRIX_LANDSCAPE 5
#define IMF_TYPE_SHADER 6
#define IMF_TYPE_SHADER_PROGRAM 7
#define IMF_TYPE_COLLISION_OBJECT 8
#define IMF_TYPE_SOUND_OBJECT 9
#define IMF_TYPE_COMPOUND_COLLISION_OBJECT 10
#define IMF_TYPE_DYNAMIC_TEXTURE 11


#define IMF_SHADER_TYPE_NULL 0
#define IMF_SHADER_TYPE_VERTEX 1
#define IMF_SHADER_TYPE_FRAGMENT 2
#define IMF_SHADER_TYPE_GEOMETRY 3

#define IMF_MODEL_VERTEX 1
#define IMF_MODEL_NORMALS 2
#define IMF_MODEL_UVS 4
#define IMF_MODEL_FACES 8

#define IMF_FONT_CHARACTERS 93
#define IMF_FONT_SCALE ((double)(1.0/IMF_FONT_CHARACTERS)-0.000001)


#define IMF_SHADERVAR_UNDEFINED 0
#define IMF_SHADERVAR_FLOAT 1
#define IMF_SHADERVAR_VEC2 2
#define IMF_SHADERVAR_VEC3 3
#define IMF_SHADERVAR_VEC4 4
#define IMF_SHADERVAR_BOOL 5
#define IMF_SHADERVAR_BVEC2 6
#define IMF_SHADERVAR_BVEC3 7
#define IMF_SHADERVAR_BVEC4 8
#define IMF_SHADERVAR_INT 9
#define IMF_SHADERVAR_IVEC2 10
#define IMF_SHADERVAR_IVEC3 11
#define IMF_SHADERVAR_IVEC4 12
#define IMF_SHADERVAR_MATRIX2 13
#define IMF_SHADERVAR_MATRIX3 14
#define IMF_SHADERVAR_MATRIX4 15
#define IMF_SHADERVAR_SAMPLER1D 16
#define IMF_SHADERVAR_SAMPLER2D 17
#define IMF_SHADERVAR_SAMPLER3D 18
#define IMF_SHADERVAR_SAMPLER4D 19


#define IMF_CCN_UNDEFINED 0x0
#define IMF_CCN_REFERENCE 0x1
#define IMF_CCN_RADIUS 0x2
#define IMF_CCN_BOX 0x3
#endif
