#ifndef __WTGAMESETTINGS_H__
#define __WTGAMESETTINGS_H__
/*
#define WT_P_MAIN_THRUST WT_TIME_IND*0.01f

#define WT_P_SECOND_THRUST WT_TIME_IND*0.002f
#define WT_P_THRUST_CHANGE WT_TIME_IND*1.0f
#define WT_P_REVERSE_THRUST 0.5f

#define WT_ENEMY_UNIT 1


#define WT_BATTERY_POWER_TO_DAMAGE_FACTOR 0.1f
*/

#endif
