#ifndef __WTKEYSTATEDEFINITIONS_H__
#define __WTKEYSTATEDEFINITIONS_H__

//#define KEY_BACKSPACE _KEY(KEY_CODE_BACKSPACE)
#define KEY_TAB _KEY(KEY_CODE_TAB)

#define KEY_ENTER _KEY(KEY_CODE_ENTER)
#define KEY_RETURN _KEY(KEY_CODE_RETURN)

#define KEY_SHIFT _KEY(KEY_CODE_SHIFT)

#define KEY_CONTROL _KEY(KEY_CODE_CONTROL)
#define KEY_CTRL _KEY(KEY_CODE_CTRL)

#define KEY_ALTERNATE _KEY(KEY_CODE_ALTERNATE)
#define KEY_ALT _KEY(KEY_CODE_ALT)

#define KEY_PAUSE _KEY(KEY_CODE_PAUSE)

#define KEY_CAPSLOCK _KEY(KEY_CODE_CAPSLOCK)
#define KEY_CAPITALLOCK _KEY(KEY_CODE_CAPITALLOCK)

#define KEY_ESCAPE _KEY(KEY_CODE_ESCAPE)
#define KEY_ESC _KEY(KEY_CODE_ESC)

#define KEY_SPACE _KEY(KEY_CODE_SPACE)

#define KEY_PGUP _KEY(KEY_CODE_PGUP)
#define KEY_PAGEUP _KEY(KEY_CODE_PAGEUP)

#define KEY_PGDN _KEY(KEY_CODE_PGDN)
#define KEY_PAGEDOWN _KEY(KEY_CODE_PAGEDOWN)

#define KEY_END _KEY(KEY_CODE_END)
#define KEY_HOME _KEY(KEY_CODE_HOME)

#define KEY_LEFT _KEY(KEY_CODE_LEFT)
#define KEY_LEFTARROW _KEY(KEY_CODE_LEFTARROW)

#define KEY_RIGHT _KEY(KEY_CODE_RIGHT)
#define KEY_RIGHTARROW _KEY(KEY_CODE_RIGHTARROW)

#define KEY_UP _KEY(KEY_CODE_UP)
#define KEY_UPARROW _KEY(KEY_CODE_UPARROW)

#define KEY_DOWN _KEY(KEY_CODE_DOWN)
#define KEY_DOWNARROW _KEY(KEY_CODE_DOWNARROW)

#define KEY_SELECT _KEY(KEY_CODE_SELECT)

#define KEY_EARLYPRINT _KEY(KEY_CODE_EARLYPRINT)
#define KEY_EARLYPRINTSCREEN _KEY(KEY_CODE_EARLYPRINTSCREEN)

#define KEY_EXECTUE _KEY(KEY_CODE_EXECUTE)

#define KEY_PRINT _KEY(KEY_CODE_PRINT)
#define KEY_PRINTSCREEN _KEY(KEY_CODE_PRINTSCREEN)

#define KEY_INS _KEY(KEY_CODE_INS)
#define KEY_INSERT _KEY(KEY_CODE_INSERT)

#define KEY_DEL _KEY(KEY_CODE_DEL)
#define KEY_DELETE _KEY(KEY_CODE_DELETE)

#define KEY_HELP _KEY(KEY_CODE_HELP)


#define KEY_0 _KEY(KEY_CODE_0)
#define KEY_1 _KEY(KEY_CODE_1)
#define KEY_2 _KEY(KEY_CODE_2)
#define KEY_3 _KEY(KEY_CODE_3)
#define KEY_4 _KEY(KEY_CODE_4)
#define KEY_5 _KEY(KEY_CODE_5)
#define KEY_6 _KEY(KEY_CODE_6)
#define KEY_7 _KEY(KEY_CODE_7)
#define KEY_8 _KEY(KEY_CODE_8)
#define KEY_9 _KEY(KEY_CODE_9)

#define KEY_NUMPAD0 _KEY(KEY_CODE_NUMPAD0)
#define KEY_NP0 _KEY(KEY_CODE_NP0)
#define KEY_NUMPAD1 _KEY(KEY_CODE_NUMPAD1)
#define KEY_NP1 _KEY(KEY_CODE_NP1)
#define KEY_NUMPAD2 _KEY(KEY_CODE_NUMPAD2)
#define KEY_NP2 _KEY(KEY_CODE_NP2)
#define KEY_NUMPAD3 _KEY(KEY_CODE_NUMPAD3)
#define KEY_NP3 _KEY(KEY_CODE_NP3)
#define KEY_NUMPAD4 _KEY(KEY_CODE_NUMPAD4)
#define KEY_NP4 _KEY(KEY_CODE_NP4)
#define KEY_NUMPAD5 _KEY(KEY_CODE_NUMPAD5)
#define KEY_NP5 _KEY(KEY_CODE_NP5)
#define KEY_NUMPAD6 _KEY(KEY_CODE_NUMPAD6)
#define KEY_NP6 _KEY(KEY_CODE_NP6)
#define KEY_NUMPAD7 _KEY(KEY_CODE_NUMPAD7)
#define KEY_NP7 _KEY(KEY_CODE_NP7)
#define KEY_NUMPAD8 _KEY(KEY_CODE_NUMPAD8)
#define KEY_NP8 _KEY(KEY_CODE_NP8)
#define KEY_NUMPAD9 _KEY(KEY_CODE_NUMPAD9)
#define KEY_NP9 _KEY(KEY_CODE_NP9)


#define KEY_A _KEY(KEY_CODE_A)
#define KEY_B _KEY(KEY_CODE_B)
#define KEY_C _KEY(KEY_CODE_C)
#define KEY_D _KEY(KEY_CODE_D)
#define KEY_E _KEY(KEY_CODE_E)
#define KEY_F _KEY(KEY_CODE_F)
#define KEY_G _KEY(KEY_CODE_G)
#define KEY_H _KEY(KEY_CODE_H)
#define KEY_I _KEY(KEY_CODE_I)
#define KEY_J _KEY(KEY_CODE_J)
#define KEY_K _KEY(KEY_CODE_K)
#define KEY_L _KEY(KEY_CODE_L)
#define KEY_M _KEY(KEY_CODE_M)
#define KEY_N _KEY(KEY_CODE_N)
#define KEY_O _KEY(KEY_CODE_O)
#define KEY_P _KEY(KEY_CODE_P)
#define KEY_Q _KEY(KEY_CODE_Q)
#define KEY_R _KEY(KEY_CODE_R)
#define KEY_S _KEY(KEY_CODE_S)
#define KEY_T _KEY(KEY_CODE_T)
#define KEY_U _KEY(KEY_CODE_U)
#define KEY_V _KEY(KEY_CODE_V)
#define KEY_W _KEY(KEY_CODE_W)
#define KEY_X _KEY(KEY_CODE_X)
#define KEY_Y _KEY(KEY_CODE_Y)
#define KEY_Z _KEY(KEY_CODE_Z)

#define KEY_a _KEY(KEY_CODE_a)
#define KEY_b _KEY(KEY_CODE_b)
#define KEY_c _KEY(KEY_CODE_c)
#define KEY_d _KEY(KEY_CODE_d)
#define KEY_e _KEY(KEY_CODE_e)
#define KEY_f _KEY(KEY_CODE_f)
#define KEY_g _KEY(KEY_CODE_g)
#define KEY_h _KEY(KEY_CODE_h)
#define KEY_i _KEY(KEY_CODE_i)
#define KEY_j _KEY(KEY_CODE_j)
#define KEY_k _KEY(KEY_CODE_k)
#define KEY_l _KEY(KEY_CODE_l)
#define KEY_m _KEY(KEY_CODE_m)
#define KEY_n _KEY(KEY_CODE_n)
#define KEY_o _KEY(KEY_CODE_o)
#define KEY_p _KEY(KEY_CODE_p)
#define KEY_q _KEY(KEY_CODE_q)
#define KEY_r _KEY(KEY_CODE_r)
#define KEY_s _KEY(KEY_CODE_s)
#define KEY_t _KEY(KEY_CODE_t)
#define KEY_u _KEY(KEY_CODE_u)
#define KEY_v _KEY(KEY_CODE_v)
#define KEY_w _KEY(KEY_CODE_w)
#define KEY_x _KEY(KEY_CODE_x)
#define KEY_y _KEY(KEY_CODE_y)
#define KEY_z _KEY(KEY_CODE_z)











#define KEY_NUMBERPAD_SUBTRACT _KEY(KEY_CODE_NUMBERPAD_SUBTRACT)
#define KEY_NP_SUBTRACT _KEY(KEY_CODE_NP_SUBTRACT)
#define KEY_NUMBERPAD_MULTIPLY _KEY(KEY_CODE_NUMBERPAD_MULTIPLY)
#define KEY_NP_MULTIPLY _KEY(KEY_CODE_NP_MULTIPLY)
#define KEY_NUMBERPAD_PLUS _KEY(KEY_CODE_NUMBERPAD_PLUS)
#define KEY_NP_PLUS _KEY(KEY_CODE_NP_PLUS)
#define KEY_NUMBERPAD_DIVIDE _KEY(KEY_CODE_NUMBERPAD_DIVIDE)
#define KEY_NP_DIVIDE _KEY(KEY_CODE_NP_DIVIDE)
#define KEY_NUMBERPAD_DECIMAL _KEY(KEY_CODE_NUMBERPAD_DECIMAL)
#define KEY_NP_DECIMAL _KEY(KEY_CODE_NP_DECIMAL)
#define KEY_NUMBERPAD_PERIOD _KEY(KEY_CODE_NUMBERPAD_PERIOD)
#define KEY_NP_PERIOD _KEY(KEY_CODE_NP_PERIOD)
#define KEY_NP_ENTER _KEY(KEY_CODE_NP_ENTER)
#define KEY_NP_RETURN _KEY(KEY_CODE_NP_RETURN)
#define KEY_NUMBERPAD_ENTER _KEY(KEY_CODE_NUMBERPAD_ENTER)
#define KEY_NUMBERPAD_RETURN _KEY(KEY_CODE_NUMBERPAD_RETURN)

#define KEY_TILDE _KEY(KEY_CODE_TILDE)
#define KEY_SEPARATOR _KEY(KEY_CODE_SEPARATOR)
#define KEY_SEMICOLON _KEY(KEY_CODE_SEMICOLON)
#define KEY_COMMA _KEY(KEY_CODE_COMMA)
#define KEY_SQUARE_BRACKET_OPEN _KEY(KEY_CODE_SQUARE_BRACKET_OPEN)
#define KEY_SBO _KEY(KEY_CODE_SBO)
#define KEY_SQUARE_BRACKET_CLOSE _KEY(KEY_CODE_SQUARE_BRACKET_CLOSE)
#define KEY_SBC _KEY(KEY_CODE_SBC)
#define KEY_BACKSLASH _KEY(KEY_CODE_BACKSLASH)
#define KEY_BACKSPACE _KEY(KEY_CODE_BACKSPACE)
#define KEY_APOSTROPHE _KEY(KEY_CODE_APOSTROPHE)
#define KEY_PERIOD _KEY(KEY_CODE_PERIOD)
#define KEY_DECIMAL _KEY(KEY_CODE_DECIMAL)
#define KEY_QUOTE _KEY(KEY_CODE_QUOTE)
#define KEY_SLASH _KEY(KEY_CODE_SLASH)
#define KEY_EQUALS _KEY(KEY_CODE_EQUALS)
#define KEY_DASH _KEY(KEY_CODE_DASH)



#define KEY_F1 _KEY(KEY_CODE_F1)
#define KEY_F2 _KEY(KEY_CODE_F2)
#define KEY_F3 _KEY(KEY_CODE_F3)
#define KEY_F4 _KEY(KEY_CODE_F4)
#define KEY_F5 _KEY(KEY_CODE_F5)
#define KEY_F6 _KEY(KEY_CODE_F6)
#define KEY_F7 _KEY(KEY_CODE_F7)
#define KEY_F8 _KEY(KEY_CODE_F8)
#define KEY_F9 _KEY(KEY_CODE_F9)
#define KEY_F10 _KEY(KEY_CODE_F10)
#define KEY_F11 _KEY(KEY_CODE_F11)
#define KEY_F12 _KEY(KEY_CODE_F12)
#define KEY_F13 _KEY(KEY_CODE_F13)
#define KEY_F14 _KEY(KEY_CODE_F14)
#define KEY_F15 _KEY(KEY_CODE_F15)
#define KEY_F16 _KEY(KEY_CODE_F16)
#define KEY_F17 _KEY(KEY_CODE_F17)
#define KEY_F18 _KEY(KEY_CODE_F18)
#define KEY_F19 _KEY(KEY_CODE_F19)
#define KEY_F20 _KEY(KEY_CODE_F20)
#define KEY_F21 _KEY(KEY_CODE_F21)
#define KEY_F22 _KEY(KEY_CODE_F22)
#define KEY_F23 _KEY(KEY_CODE_F23)
#define KEY_F24 _KEY(KEY_CODE_F24)



#endif
