

#if WT_OS_TYPE==OS_WIN32

/* These are the key codes converted from Windows virtual keys. All keys begin
    with KEY_ and end with either the long or short version of the key name  */
//#define KEY_CODE_BACKSPACE (VK_BACK)
#define KEY_CODE_TAB (VK_TAB)

#define KEY_CODE_ENTER (VK_RETURN)
#define KEY_CODE_RETURN (VK_RETURN)

#define KEY_CODE_SHIFT (VK_SHIFT)

#define KEY_CODE_CONTROL (VK_CONTROL)
#define KEY_CODE_CTRL (VK_CONTROL)

#define KEY_CODE_ALTERNATE (VK_MENU)
#define KEY_CODE_ALT (VK_MENU)

#define KEY_CODE_PAUSE (VK_PAUSE)

#define KEY_CODE_CAPSLOCK (VK_CAPITAL)
#define KEY_CODE_CAPITALlOCK (VK_CAPITAL)

#define KEY_CODE_ESCAPE (VK_ESCAPE)
#define KEY_CODE_ESC (VK_ESCAPE)

#define KEY_CODE_SPACE (VK_SPACE)

#define KEY_CODE_PGUP (VK_PRIOR)
#define KEY_CODE_PAGEUP (VK_PRIOR)

#define KEY_CODE_PGDN (VK_NEXT)
#define KEY_CODE_PAGEDOWN (VK_NEXT)

#define KEY_CODE_END (VK_END)
#define KEY_CODE_HOME (VK_HOME)

#define KEY_CODE_LEFT (VK_LEFT)
#define KEY_CODE_LEFTARROW (VK_LEFT)

#define KEY_CODE_RIGHT (VK_RIGHT)
#define KEY_CODE_RIGHTARROW (VK_RIGHT)

#define KEY_CODE_UP (VK_UP)
#define KEY_CODE_UPARROW (VK_UP)

#define KEY_CODE_DOWN (VK_DOWN)
#define KEY_CODE_DOWNARROW (VK_DOWN)

#define KEY_CODE_SELECT (VK_SELECT)

#define KEY_CODE_EARLYPRINT (VK_PRINT)
#define KEY_CODE_EARLYPRINTSCREEN (VK_PRINT)

#define KEY_CODE_EXECTUE (VK_EXECUTE)

#define KEY_CODE_PRINT (VK_SNAPSHOT)
#define KEY_CODE_PRINTSCREEN (VK_SNAPSHOT)

#define KEY_CODE_INS (VK_INSERT)
#define KEY_CODE_INSERT (VK_INSERT)

#define KEY_CODE_DEL (VK_DELETE)
#define KEY_CODE_DELETE (VK_DELETE)

#define KEY_CODE_HELP (VK_HELP)


#define KEY_CODE_0 (0x30)
#define KEY_CODE_1 (0x31)
#define KEY_CODE_2 (0x32)
#define KEY_CODE_3 (0x33)
#define KEY_CODE_4 (0x34)
#define KEY_CODE_5 (0x35)
#define KEY_CODE_6 (0x36)
#define KEY_CODE_7 (0x37)
#define KEY_CODE_8 (0x38)
#define KEY_CODE_9 (0x39)

#define KEY_CODE_A (0x41)
#define KEY_CODE_B (0x42)
#define KEY_CODE_C (0x43)
#define KEY_CODE_D (0x44)
#define KEY_CODE_E (0x45)
#define KEY_CODE_F (0x46)
#define KEY_CODE_G (0x47)
#define KEY_CODE_H (0x48)
#define KEY_CODE_I (0x49)
#define KEY_CODE_J (0x4A)
#define KEY_CODE_K (0x4B)
#define KEY_CODE_L (0x4C)
#define KEY_CODE_M (0x4D)
#define KEY_CODE_N (0x4E)
#define KEY_CODE_O (0x4F)
#define KEY_CODE_P (0x50)
#define KEY_CODE_Q (0x51)
#define KEY_CODE_R (0x52)
#define KEY_CODE_S (0x53)
#define KEY_CODE_T (0x54)
#define KEY_CODE_U (0x55)
#define KEY_CODE_V (0x56)
#define KEY_CODE_W (0x57)
#define KEY_CODE_X (0x58)
#define KEY_CODE_Y (0x59)
#define KEY_CODE_Z (0x5A)

#define KEY_CODE_a (0x41)
#define KEY_CODE_b (0x42)
#define KEY_CODE_c (0x43)
#define KEY_CODE_d (0x44)
#define KEY_CODE_e (0x45)
#define KEY_CODE_f (0x46)
#define KEY_CODE_g (0x47)
#define KEY_CODE_h (0x48)
#define KEY_CODE_i (0x49)
#define KEY_CODE_j (0x4A)
#define KEY_CODE_k (0x4B)
#define KEY_CODE_l (0x4C)
#define KEY_CODE_m (0x4D)
#define KEY_CODE_n (0x4E)
#define KEY_CODE_o (0x4F)
#define KEY_CODE_p (0x50)
#define KEY_CODE_q (0x51)
#define KEY_CODE_r (0x52)
#define KEY_CODE_s (0x53)
#define KEY_CODE_t (0x54)
#define KEY_CODE_u (0x55)
#define KEY_CODE_v (0x56)
#define KEY_CODE_w (0x57)
#define KEY_CODE_x (0x58)
#define KEY_CODE_y (0x59)
#define KEY_CODE_z (0x5A)





#define KEY_CODE_NUMPAD0 VK_NUMPAD0
#define KEY_CODE_NP0 VK_NUMPAD0
#define KEY_CODE_NUMPAD1 VK_NUMPAD1
#define KEY_CODE_NP1 VK_NUMPAD1
#define KEY_CODE_NUMPAD2 VK_NUMPAD2
#define KEY_CODE_NP2 VK_NUMPAD2
#define KEY_CODE_NUMPAD3  VK_NUMPAD3
#define KEY_CODE_NP3  VK_NUMPAD3
#define KEY_CODE_NUMPAD4 VK_NUMPAD4
#define KEY_CODE_NP4 VK_NUMPAD4
#define KEY_CODE_NUMPAD5 VK_NUMPAD5
#define KEY_CODE_NP5 VK_NUMPAD5
#define KEY_CODE_NUMPAD6 VK_NUMPAD6
#define KEY_CODE_NP6 VK_NUMPAD6
#define KEY_CODE_NUMPAD7 VK_NUMPAD7
#define KEY_CODE_NP7 VK_NUMPAD7
#define KEY_CODE_NUMPAD8 VK_NUMPAD8
#define KEY_CODE_NP8 VK_NUMPAD8
#define KEY_CODE_NUMPAD9 VK_NUMPAD9
#define KEY_CODE_NP9 VK_NUMPAD9

#define KEY_CODE_NUMBERPAD_SUBTRACT VK_SUBTRACT
#define KEY_CODE_NP_SUBTRACT VK_SUBTRACT
#define KEY_CODE_NUMBERPAD_MULTIPLY VK_MULTIPLY
#define KEY_CODE_NP_MULTIPLY VK_MULTIPLY
#define KEY_CODE_NUMBERPAD_PLUS VK_ADD
#define KEY_CODE_NP_PLUS VK_ADD
#define KEY_CODE_NUMBERPAD_DIVIDE VK_DIVIDE
#define KEY_CODE_NP_DIVIDE VK_DIVIDE
#define KEY_CODE_NUMBERPAD_DECIMAL VK_DECIMAL
#define KEY_CODE_NP_DECIMAL VK_DECIMAL
#define KEY_CODE_NUMBERPAD_PERIOD VK_DECIMAL
#define KEY_CODE_NP_PERIOD VK_DECIMAL
#define KEY_CODE_NUMBERPAD_ENTER VK_SEPARATOR
#define KEY_CODE_NP_ENTER VK_SEPARATOR
#define KEY_CODE_NUMBERPAD_RETURN VK_SEPARATOR
#define KEY_CODE_NP_RETURN VK_SEPARATOR

#define KEY_CODE_TILDE 196
#define KEY_CODE_SEPARATOR VK_SEPARATOR
#define KEY_CODE_SEMICOLON VK_OEM_1
#define KEY_CODE_COMMA VK_OEM_COMMA
#define KEY_CODE_SQUARE_BRACKET_OPEN VK_OEM_4
#define KEY_CODE_SBO VK_OEM_4
#define KEY_CODE_SQUARE_BRACKET_CLOSE VK_OEM_6
#define KEY_CODE_SBC VK_OEM_6
#define KEY_CODE_BACKSLASH VK_OEM_5
#define KEY_CODE_BACKSPACE VK_BACK_SPACE
#define KEY_CODE_APOSTROPHE VK_OEM_3
#define KEY_CODE_PERIOD VK_OEM_PERIOD
#define KEY_CODE_DECIMAL VK_OEM_PERIOD
#define KEY_CODE_QUOTE VK_OEM_7
#define KEY_CODE_SLASH VK_OEM_2
#define KEY_CODE_EQUALS VK_OEM_PLUS
#define KEY_CODE_DASH VK_OEM_MINUS

#define KEY_CODE_F1 VK_F1
#define KEY_CODE_F2 VK_F2
#define KEY_CODE_F3 VK_F3
#define KEY_CODE_F4 VK_F4
#define KEY_CODE_F5 VK_F5
#define KEY_CODE_F6 VK_F6
#define KEY_CODE_F7 VK_F7
#define KEY_CODE_F8 VK_F8
#define KEY_CODE_F9 VK_F9
#define KEY_CODE_F10 VK_F10
#define KEY_CODE_F11 VK_F11
#define KEY_CODE_F12 VK_F12
#define KEY_CODE_F13 VK_F13
#define KEY_CODE_F14 VK_F14
#define KEY_CODE_F15 VK_F15
#define KEY_CODE_F16 VK_F16
#define KEY_CODE_F17 VK_F17
#define KEY_CODE_F18 VK_F18
#define KEY_CODE_F19 VK_F19
#define KEY_CODE_F20 VK_F20
#define KEY_CODE_F21 VK_F21
#define KEY_CODE_F22 VK_F22
#define KEY_CODE_F23 VK_F23
#define KEY_CODE_F24 VK_F24


#endif
