

#if WT_OS_TYPE==OS_LINUX

// These are the key codes converted from Windows virtual keys. All keys begin with KEY_ and end with either the long or short version of the key name

//#define KEY_CODE_BACKSPACE (XK_BackSpace&0xFF)
#define KEY_CODE_TAB (XK_Tab&0xFF)

#define KEY_CODE_ENTER (XK_Return&0xFF)
#define KEY_CODE_RETURN (XK_Return&0xFF)

#define KEY_CODE_LEFT_SHIFT (XK_Shift_L&0xff)
#define KEY_CODE_RIGHT_SHIFT (XK_Shift_R&0xff)
#define KEY_CODE_SHIFT (XK_Shift_L&0xFF)

#define KEY_CODE_LEFT_CONTROL (XK_Control_L&0xff)
#define KEY_CODE_RIGHT_CONTROL (XK_Control_R&0xff)
#define KEY_CODE_LCTRL (XK_Control_L&0xff)
#define KEY_CODE_RCTRL (XK_Control_R&0xff)
#define KEY_CODE_CTRL (XK_Control_L&0xff)

#define KEY_CODE_LEFT_ALTERNATE (XK_Alt_L&0xff)
#define KEY_CODE_RIGHT_ALTERNATE (XK_Alt_R&0xff)
#define KEY_CODE_LALT (XK_Alt_L&0xff)
#define KEY_CODE_RALT (XK_Alt_R&0xff)

#define KEY_CODE_PAUSE (XK_Pause&0xFF)

#define KEY_CODE_CAPSLOCK (XK_Caps_Lock&0xFF)
#define KEY_CODE_CAPITALLOCK (XK_Caps_Lock&0xFF)

#define KEY_CODE_ESCAPE (XK_Escape&0xFF)
#define KEY_CODE_ESC (XK_Escape&0xFF)

#define KEY_CODE_SPACE (XK_space&0xFF)

#define KEY_CODE_PGUP (XK_Page_Up&0xFF)
#define KEY_CODE_PAGEUP (XK_Page_Down&0xFF)

#define KEY_CODE_PGDN (XK_Page_Down&0xFF)
#define KEY_CODE_PAGEDOWN (XK_Page_Down&0xFF)

#define KEY_CODE_END (XK_End&0xFF)
#define KEY_CODE_HOME (XK_Home&0xFF)

#define KEY_CODE_LEFT (XK_Left&0xFF)
#define KEY_CODE_LEFTARROW (XK_Left&0xFF)

#define KEY_CODE_RIGHT (XK_Right & 0xFF)
#define KEY_CODE_RIGHTARROW (XK_Right&0xFF)

#define KEY_CODE_UP (XK_Up & 0xFF)
#define KEY_CODE_UPARROW (XK_Up&0xFF)

#define KEY_CODE_DOWN (XK_Down & 0xFF)
#define KEY_CODE_DOWNARROW (XK_Down&0xFF)

#define KEY_CODE_SELECT (XK_Select&0xFF)

#define KEY_CODE_EARLYPRINT (XK_Print&0xFF)
#define KEY_CODE_EARLYPRINTSCREEN (XK_Print&0xFF)

#define KEY_CODE_EXECUTE (XK_Execute&0xFF)

#define KEY_CODE_PRINT (XK_Print&0xFF)
#define KEY_CODE_PRINTSCREEN (XK_Print&0xFF)

#define KEY_CODE_INS (XK_Insert&0xFF)
#define KEY_CODE_INSERT (XK_Insert&0xFF)

#define KEY_CODE_DEL (XK_Delete&0xFF)
#define KEY_CODE_DELETE (XK_Delete&0xFF)

#define KEY_CODE_HELP (XK_Help&0xFF)

#define KEY_CODE_0 (XK_0&0xFF)
#define KEY_CODE_1 (XK_1&0xFF)
#define KEY_CODE_2 (XK_2&0xFF)
#define KEY_CODE_3 (XK_3&0xFF)
#define KEY_CODE_4 (XK_4&0xFF)
#define KEY_CODE_5 (XK_5&0xFF)
#define KEY_CODE_6 (XK_6&0xFF)
#define KEY_CODE_7 (XK_7&0xFF)
#define KEY_CODE_8 (XK_8&0xFF)
#define KEY_CODE_9 (XK_9&0xFF)

#define KEY_CODE_NUMPAD0 (VK_KP_0&0xFF)
#define KEY_CODE_NP0 (XK_KP_0&0xFF)
#define KEY_CODE_NUMPAD1 (VK_KP_1&0xFF)
#define KEY_CODE_NP1 (XK_KP_1&0xFF)
#define KEY_CODE_NUMPAD2 (VK_KP_2&0xFF)
#define KEY_CODE_NP2 (XK_KP_2&0xFF)
#define KEY_CODE_NUMPAD3 (VK_KP_3&0xFF)
#define KEY_CODE_NP3 (XK_KP_3&0xFF)
#define KEY_CODE_NUMPAD4 (VK_KP_4&0xFF)
#define KEY_CODE_NP4 (XK_KP_4&0xFF)
#define KEY_CODE_NUMPAD5 (VK_KP_5&0xFF)
#define KEY_CODE_NP5 (XK_KP_5&0xFF)
#define KEY_CODE_NUMPAD6 (VK_KP_6&0xFF)
#define KEY_CODE_NP6 (XK_KP_6&0xFF)
#define KEY_CODE_NUMPAD7 (VK_KP_7&0xFF)
#define KEY_CODE_NP7 (XK_KP_7&0xFF)
#define KEY_CODE_NUMPAD8 (VK_KP_8&0xFF)
#define KEY_CODE_NP8 (XK_KP_8&0xFF)
#define KEY_CODE_NUMPAD9 (VK_KP_9&0xFF)
#define KEY_CODE_NP9 (XK_KP_9&0xFF)

#define KEY_CODE_F1 (XK_F1&0xFF)
#define KEY_CODE_F2 (XK_F2&0xFF)
#define KEY_CODE_F3 (XK_F3&0xFF)
#define KEY_CODE_F4 (XK_F4&0xFF)
#define KEY_CODE_F5 (XK_F5&0xFF)
#define KEY_CODE_F6 (XK_F6&0xFF)
#define KEY_CODE_F7 (XK_F7&0xFF)
#define KEY_CODE_F8 (XK_F8&0xFF)
#define KEY_CODE_F9 (XK_F9&0xFF)
#define KEY_CODE_F10 (XK_F10&0xFF)
#define KEY_CODE_F11 (XK_F11&0xFF)
#define KEY_CODE_F12 (XK_F12&0xFF)

#define KEY_CODE_NUMBERPAD_SUBTRACT (XK_KP_Subtract&0xFF)
#define KEY_CODE_NP_SUBTRACT (XK_KP_Subtract&0xFF)
#define KEY_CODE_NUMBERPAD_MULTIPLY (XK_KP_Multiply&0xFF)
#define KEY_CODE_NP_MULTIPLY (XK_KP_Multiply&0xFF)
#define KEY_CODE_NUMBERPAD_PLUS (XK_KP_Add&0xFF)
#define KEY_CODE_NP_PLUS (XK_KP_Add&0xFF)
#define KEY_CODE_NUMBERPAD_DIVIDE (XK_KP_Divide&0xFF)
#define KEY_CODE_NP_DIVIDE (XK_KP_Divide&0xFF)
#define KEY_CODE_NUMBERPAD_DECIMAL (XK_KP_Decimal&0xFF)
#define KEY_CODE_NP_DECIMAL (XK_KP_Decimal&0xFF)
#define KEY_CODE_NUMBERPAD_PERIOD (XK_KP_Decimal&0xFF)
#define KEY_CODE_NP_PERIOD (XK_KP_Decimal&0xFF)
#define KEY_CODE_NP_ENTER (XK_KP_Enter&0xff)
#define KEY_CODE_NP_RETURN (XK_KP_Enter&0xff)
#define KEY_CODE_NUMBERPAD_ENTER (XK_KP_Enter&0xff)
#define KEY_CODE_NUMBERPAD_RETURN (XK_KP_Enter&0xff)

#define KEY_CODE_TILDE (XK_GRAVE&0xFF)
#define KEY_CODE_SEPARATOR (XK_separator&0xFF)
#define KEY_CODE_SEMICOLON (XK_semicolon&0xFF)
#define KEY_CODE_COMMA (XK_comma&0xFF)
#define KEY_CODE_SQUARE_BRACKET_OPEN (XK_bracketleft&0xFF)
#define KEY_CODE_SBO (XK_bracketleft&0xFF)
#define KEY_CODE_SQUARE_BRACKET_CLOSE (XK_bracketright&0xFF)
#define KEY_CODE_SBC (XK_bracketright&0xFF)
#define KEY_CODE_BACKSLASH (XK_backslash&0xFF)
#define KEY_CODE_BACKSPACE (XK_BackSpace&0xFF)
#define KEY_CODE_APOSTROPHE (XK_apostrophe&0xFF)
#define KEY_CODE_PERIOD (XK_period&0xFF)
#define KEY_CODE_DECIMAL (XK_period&0xFF)
#define KEY_CODE_QUOTE (XK_quoteleft&0xfF)
#define KEY_CODE_SLASH (XK_slash&0xFF)
#define KEY_CODE_EQUALS (XK_equal&0xff)
#define KEY_CODE_DASH (XK_minus&0xff)

#define KEY_CODE_A (XK_A&0xFF)
#define KEY_CODE_B (XK_B&0xFF)
#define KEY_CODE_C (XK_C&0xFF)
#define KEY_CODE_D (XK_D&0xFF)
#define KEY_CODE_E (XK_E&0xFF)
#define KEY_CODE_F (XK_F&0xFF)
#define KEY_CODE_G (XK_G&0xFF)
#define KEY_CODE_H (XK_H&0xFF)
#define KEY_CODE_I (XK_I&0xFF)
#define KEY_CODE_J (XK_J&0xFF)
#define KEY_CODE_K (XK_K&0xFF)
#define KEY_CODE_L (XK_L&0xFF)
#define KEY_CODE_M (XK_M&0xFF)
#define KEY_CODE_N (XK_N&0xFF)
#define KEY_CODE_O (XK_O&0xFF)
#define KEY_CODE_P (XK_P&0xFF)
#define KEY_CODE_Q (XK_Q&0xFF)
#define KEY_CODE_R (XK_R&0xFF)
#define KEY_CODE_S (XK_S&0xFF)
#define KEY_CODE_T (XK_T&0xFF)
#define KEY_CODE_U (XK_U&0xFF)
#define KEY_CODE_V (XK_V&0xFF)
#define KEY_CODE_W (XK_W&0xFF)
#define KEY_CODE_X (XK_X&0xFF)
#define KEY_CODE_Y (XK_Y&0xFF)
#define KEY_CODE_Z (XK_Z&0xFF)

#define KEY_CODE_a (XK_a&0xFF)
#define KEY_CODE_b (XK_b&0xFF)
#define KEY_CODE_c (XK_c&0xFF)
#define KEY_CODE_d (XK_d&0xFF)
#define KEY_CODE_e (XK_e&0xFF)
#define KEY_CODE_f (XK_f&0xFF)
#define KEY_CODE_g (XK_g&0xFF)
#define KEY_CODE_h (XK_h&0xFF)
#define KEY_CODE_i (XK_i&0xFF)
#define KEY_CODE_j (XK_j&0xFF)
#define KEY_CODE_k (XK_k&0xFF)
#define KEY_CODE_l (XK_l&0xFF)
#define KEY_CODE_m (XK_m&0xFF)
#define KEY_CODE_n (XK_n&0xFF)
#define KEY_CODE_o (XK_o&0xFF)
#define KEY_CODE_p (XK_p&0xFF)
#define KEY_CODE_q (XK_q&0xFF)
#define KEY_CODE_r (XK_r&0xFF)
#define KEY_CODE_s (XK_s&0xFF)
#define KEY_CODE_t (XK_t&0xFF)
#define KEY_CODE_u (XK_u&0xFF)
#define KEY_CODE_v (XK_v&0xFF)
#define KEY_CODE_w (XK_w&0xFF)
#define KEY_CODE_x (XK_x&0xFF)
#define KEY_CODE_y (XK_y&0xFF)
#define KEY_CODE_z (XK_z&0xFF)


#endif
